"""initial

Revision ID: 190cd01d8d09
Revises: 
Create Date: 2025-07-26 08:52:21.652935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '190cd01d8d09'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_config',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('config_key', sa.String(length=50), nullable=False),
    sa.Column('config_value', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key')
    )
    op.create_table('travel_document_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('origin_country', sa.String(length=100), nullable=False),
    sa.Column('destination_country', sa.String(length=100), nullable=False),
    sa.Column('visa_documents', sa.Text(), nullable=True),
    sa.Column('passport_requirements', sa.Text(), nullable=True),
    sa.Column('additional_documents', sa.Text(), nullable=True),
    sa.Column('travel_advisories', sa.Text(), nullable=True),
    sa.Column('queried_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('travel_document_queries')
    op.drop_table('application_config')
    # ### end Alembic commands ###
